[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
fnsql = { version = "*", features = ["all"] }
postgres = "0.19"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
arbitrary = { version = "1", features = ["derive"] }
